### ISSUE TITLE
Dummy App New User Form Error

### ISSUE THREAD

**Issue by jacobdaddario** [excid3/madmin#101]
I'm receiving this error when trying to see the form for creating a new User.
<img width="1137" alt="Screen Shot 2021-09-24 at 12 43 16 AM" src="https://user-images.githubusercontent.com/20427632/134624237-efaaa0f4-aa59-438e-ae5f-597eaa2b8946.png">
I'll dig into it when I have a moment, for now I'm just dropping this issue on the repo to document what was happening. Something being skipped is coming back as an integer so I'll have to investigate why that's the cause. Actually taking a look at the screenshot again, I think the method just needs to be a little more type aware.

**Comment by excid3** [comment]
Fixed this. The attributes list changed from an array to hash for faster lookup. I don't think the nested forms ever got updated for that.

Also introduced some integration tests so we can make sure this continues to work. 👍

**Comment by jacobdaddario** [comment]
Sweet! I'm bummed you beat me to this.
