### ISSUE TITLE
Relation fields in forms are not working

### ISSUE THREAD

**Issue by moveson** [excid3/madmin#102]
For models that have relations, the forms provide fields that purport to reference a `select` Stimulus controller: https://github.com/excid3/madmin/blob/master/app/views/madmin/fields/has_many/_form.html.erb#L4

These fields are not working for me. I believe they are supposed to be referencing a controller built into `views/madmin/application/_javascript.html.erb`. 

In my browser console, I'm seeing the following:
```
SyntaxError: Importing binding name 'Controller' is not found.
```

Any idea how to fix this?

**Comment by moveson** [comment]
The problem may be in skypack. I'm seeing an error message when I try to access https://cdn.skypack.dev/stimulus
```
/*
 * [Package Error] "stimulus@v3.0.0" could not be built. 
 *
 *   [1/5] Verifying package is valid…
 *   [2/5] Installing dependencies from npm…
 *   [3/5] Building package using esinstall…
 *   Running esinstall...
 *   We resolved "stimulus" to stimulus/dist/stimulus.esm.js, but the file does not exist on disk.
 *   We resolved "stimulus" to /tmp/cdn/_AUDjPyNJUBKV1RspSmVm/node_modules/stimulus/dist/stimulus.esm.js, but the file does not exist on disk.
 *
 * How to fix:
 *   - If you believe this to be an error in Skypack, file an issue here: https://github.com/skypackjs/skypack-cdn/issues
 *   - If you believe this to be an issue in the package, share this URL with the package authors to help them debug & fix.
 *   - Use https://skypack.dev/ to find a web-friendly alternative to find another package.
 */
```

**Comment by excid3** [comment]
Stimulus 3.0 just came out and it's now a shim for `@hotwired/stimulus` so we probably need to swap to that package instead.
