### ISSUE TITLE
Build Error with Skypack

### ISSUE THREAD

**Issue by jacobdaddario** [excid3/madmin#104]
Looks like something is breaking with Skypack when trying to build `stimulus-flatpickr`.
<img width="569" alt="Screen Shot 2021-10-03 at 11 14 57 AM" src="https://user-images.githubusercontent.com/20427632/135762488-7a5197ba-f600-4b95-80a5-36ec88181c0c.png">
I originally encountered this error when trying to pull down updates to my fork so I could rebase #89 on top of it. I pulled down a fresh clone and confirmed that this is happening even on fresh installs.

It's breaking all Stimulus behavior, so I'll try and get this figured out so that Stimulus behavior isn't broken.

**Comment by excid3** [comment]
Stimulus-flatpickr isn't compatible with @hotwired/stimulus 3.0 yet. There's a beta release that can be used.

https://github.com/adrienpoly/stimulus-flatpickr/tree/stimulus-3

**Comment by jacobdaddario** [comment]
> Stimulus-flatpickr isn't compatible with @hotwired/stimulus 3.0 yet. There's a beta release that can be used.
> 
> https://github.com/adrienpoly/stimulus-flatpickr/tree/stimulus-3

I was just about to say that I think that Stimulus Flatpickr was pulling down the wrong version of Stimulus or had incompatibility issues. Let me try dropping in the beta release.

Edit: Yep, in [this commit](https://github.com/adrienpoly/stimulus-flatpickr/commit/fdc6fb4a13ca27facbfc3872e73a355b40598079) Adrien changes it to point to the new listing on NPM. I'll drop in his beta branch and I'll let you know if things are resolved.
