### ISSUE TITLE
edit user model with devise will cause error

### ISSUE THREAD

**Issue by jitingcn** [excid3/madmin#119]
Edit user model with devise will cause an error on reset_password_token attribute when edit other attribute and leave reset_password_token empty.

```
ActiveRecord::RecordNotUnique: PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "index_users_on_reset_password_token"
DETAIL:  Key (reset_password_token)=() already exists.
' duration=1331.64 view=0.00 db=20.52
FATAL -- :  ActiveRecord::RecordNotUnique (PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "index_users_on_reset_password_token"
DETAIL:  Key (reset_password_token)=() already exists.
```

Notice that reset_password_token should be null, but after update, it will be set to empty string.

**Comment by excid3** [comment]
You should probably set `form: false` on those fields. I don't think you want to edit those.
