### ISSUE TITLE
Relax Pagy dependencies

### ISSUE THREAD

**Issue by gathuku** [excid3/madmin#122]
@excid3  Pagy has released a lot last month https://rubygems.org/gems/pagy/versions, would you like to relax dependencies.
https://github.com/excid3/madmin/blob/5ef1dfd0c4fbed5abfb606c610533bb05b846537/madmin.gemspec#L22

**Comment by excid3** [comment]
It always depends on what the breaking changes are.

Looks like 5.0 introduced a few: https://github.com/ddnexus/pagy/blob/master/CHANGELOG.md#breaking-changes---1-code-update

If we update the Madmin code, we can change to support `>= 5.0` and `< 6.0`
