### ISSUE TITLE
forms + typography have stopped resolving

### ISSUE THREAD

**Issue by ryw** [excid3/madmin#141]
These lines are not resolving for me to valid URLs from madmin's `application.html.erb` template.

```
<link href="https://unpkg.com/@tailwindcss/forms/dist/forms.min.css" rel="stylesheet" />
<link href="https://unpkg.com/@tailwindcss/typography/dist/typography.min.css" rel="stylesheet" />
```

In my main Rails app I get forms + typograhy by adding plugins to my `tailwind.config.js` file:

# tailwind.config.js
```module.exports = {
  content: ["./app/**/*.{html,js,erb}"],
  theme: {
    extend: {},
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/typography'),
  ],
}
```

I don't know tailwind very well, so raising an issue here, maybe there is an easy fix?

**Comment by ryw** [comment]
Any plans to release a fixed version?

**Comment by excid3** [comment]
This should be fixed now.

**Comment by ryw** [comment]
This issue may have returned :( I'm seeing:

https://unpkg.com/@tailwindcss/forms/dist/forms.min.css
[Error] Failed to load resource: the server responded with a status of 404 () (forms.min.css, line 0)

https://unpkg.com/@tailwindcss/typography/dist/typography.min.css
[Error] Failed to load resource: the server responded with a status of 404 () (typography.min.css, line 0)

**Comment by ryw** [comment]
Maybe a clue for a fix
https://github.com/tailwindlabs/tailwindcss-forms/issues/110#issuecomment-1147130799

**Comment by ryw** [comment]
Well I see you've done that already via https://github.com/excid3/madmin/commit/1d9595e939bc82b53b019bc3d02a2876e84540df hmm

**Comment by ryw** [comment]
I was still on "1.2.6" never mind :(
