### ISSUE TITLE
key not found: :Inet

### ISSUE THREAD

**Issue by chenjau** [excid3/madmin#15]
ruby: 3.0.0
rails: 6.1.1
madmin: v0.1.1

definition: 
t.citext :username, null: false, default: ''
t.inet    :current_sign_in_ip

errors:
key not found: :inet
key not found: :citext
... and may be other postgresql types too(not tested)

**Comment by excid3** [comment]
Yep, we haven't done much of any database specific types yet.

We'll get to these soon. They can probably be treated and strings for the purposes of madmin.

**Comment by excid3** [comment]
Full list of supported datatypes for PG:

https://github.com/rails/rails/blob/main/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb#L101
