### ISSUE TITLE
about schema_migrations_* / data_schema_migrations_*

### ISSUE THREAD

**Issue by chenjau** [excid3/madmin#16]
ruby: 3.0.0
rails: 6.1.1
madmin: v0.1.1

after `rails g madmin:install`, madmin generator created following files:

controllers
├── madmin
 │   ├── active_record
 │    │   └── schema_migrations_controller.rb
 │   ├── data_migrate
 │    │   └── data_schema_migrations_controller.rb
 │   └── users_controller.rb

madmin
└── resources
    ├── active_record
     │   └── schema_migration_resource.rb
    ├── data_migrate
     │   └── data_schema_migration_resource.rb
    └── user_resource.rb

what are the purpose of these schema_migrations_* ? is this on purpose or bug? thanks

**Comment by afomera** [comment]
Hi @chenjau can you tell us if you have a model for those in your app? 🤔

**Comment by chenjau** [comment]
Hi! just an user model: 
models
├── application_record.rb
├── concerns
└── user.rb

after comment out gem '[data_migrate](https://github.com/ilyakatz/data-migrate)' , and tried `rails g madmin:install` again, madmin generated following files as expected:
$ rails g madmin:install
route  root to: "dashboard#show"
create  app/madmin/resources/user_resource.rb
create  app/controllers/madmin/users_controller.rb
route  resources :users

**Comment by excid3** [comment]
Madmin will generate resources for any models from your app and any gems you include. Sounds like the `data_migrate` gem provides models, so that's where it was coming from. 

Working as expected to me. 👍
