### ISSUE TITLE
Update tailwindcss-stimulus-components

### ISSUE THREAD

**Issue by MaxenceLenoir** [excid3/madmin#173]
Hey Chris,

First of all, thank you for this project, it's really useful !

I noticed an issue since the last [tailwindcss-stimulus-components](https://github.com/excid3/tailwindcss-stimulus-components) release.

I think there is still an old url for "tailwindcss-stimulus-components" importmap that breaks the javascript.

~~"tailwindcss-stimulus-components": "https://unpkg.com/tailwindcss-stimulus-components/dist/tailwindcss-stimulus-components.modern.js"~~
"tailwindcss-stimulus-components": "https://unpkg.com/tailwindcss-stimulus-components/dist/tailwindcss-stimulus-components.module.js"

**Comment by excid3** [comment]
Thanks @MaxenceLenoir. Want to send me a PR?

**Comment by MaxenceLenoir** [comment]
Yes, I would appreciate.
