### ISSUE TITLE
to_param causing issues

### ISSUE THREAD

**Issue by Shpigford** [excid3/madmin#180]
I have to_param set for a model:

```
class Term < ApplicationRecord
  def to_param
    slug
  end
end
```

When I try to view or edit a "term" in madmin, it's throwing an ActiveRecord::RecordNotFound error:

![CleanShot 2023-11-07 at 14 20 17@2x](https://github.com/excid3/madmin/assets/35243/d3d39bbf-b7e9-411d-a41f-bec16db3eb71)

I may have missed something in the docs about handling to_param but didn't immediately find much.

**Comment by excid3** [comment]
Madmin just calls `find(params[:id])` basically, so it would be querying against the primary key column for `"adjudicate"`.

If you override the `model_find` class method in your resource, you can have it query against `slug`

```ruby
class TermResource < Madmin::Resource
  def self.model_find(id)
    model.find_by!(slug: id)
  end
end
```

**Comment by Shpigford** [comment]
Oh perfect! That did the trick. Thanks!
