### ISSUE TITLE
Show * for required fields

### ISSUE THREAD

**Issue by excid3** [excid3/madmin#19]
You can access the validators on a model by doing:

```ruby
User._validators
```

We can use this to render an asterisk or note for required fields.

```ruby
User._validators[:email].any? { |v| v.is_a? ActiveModel::Validations::PresenceValidator }
```

Todos:
- [x] `required?` method on Field
- [x] Add `* Required` label when rendering fields

**Comment by excid3** [comment]
Started on this by adding a `required?` method to `Madmin::Field`

**Comment by fiveNinePlusR** [comment]
Would you want this to be added to each of the resource `_form` views or to the main application `_form` view?

**Comment by excid3** [comment]
@fiveNinePlusR I _think_ it probably needs to be in the resource `_form` views because they may differ depending on the field type. And we can probably add `required: true` to the fields as well.
