### ISSUE TITLE
Import map not resolving actiontext

### ISSUE THREAD

**Issue by moladukes** [excid3/madmin#191]
`https://unpkg.com/@rails/actiontext@7.0.3-1/app/assets/javascripts/actiontext.js net::ERR_ABORTED 404 (Not Found)`

<img width="832" alt="Screenshot 2024-01-17 at 1 13 23 PM" src="https://github.com/excid3/madmin/assets/1104139/f0dcf4da-78af-4ef0-a687-0f94f2b48706">

**Comment by raphaeljlps** [comment]
Same issue here

**Comment by excid3** [comment]
We're now using Trix from the asset pipeline instead of CDN. 👍
