### ISSUE TITLE
Allow registering new fields & column types

### ISSUE THREAD

**Issue by excid3** [excid3/madmin#20]
Right now we have a hardcoded hash of column types and fields. Users will probably want to customize this, so we should make this something they can modify.

**Comment by spacerobotTR** [comment]
If I need to add more fields to the user model now, where would I do that exactly?

**Comment by excid3** [comment]
@spacerobotTR can you post that in Discussions instead?

**Comment by spacerobotTR** [comment]
Thanks. Sorry I ended up figuring it out. I am really liking this so far!

**Comment by dp6ai** [comment]
@excid3 and @spacerobotTR is this documented anywhere? I'd be interested in adding a condensed (less padding etc) version of nested_has_many for specific resources. 

Thanks

**Comment by fiveNinePlusR** [comment]
@dp6ai looks like the list is here: https://github.com/excid3/madmin/blob/master/lib/madmin/resource.rb#L90

would need an interface to configure that in some way. probably loading from a configuration file and the associated baggage that entails.

**Comment by excid3** [comment]
I think we will probably add a `field: CustomField` option for the attribute in the Resource class for supporting custom fields.

**Comment by excid3** [comment]
Just added!
