### ISSUE TITLE
uninitialized constant Madmin::ActiveRecord::Enum

### ISSUE THREAD

**Issue by clayton** [excid3/madmin#200]
Installed Madmin on a fairly vanilla rails app (using SQLite) and I'm getting an error when trying to load my UserResource inside of `MAdmin::Resource`

The raised error looks odd because it says "Can't find X looking in [X, Y, Z]" but the actual error is that `ActiveRecord::Enum` can't  be found when inferring types in the `infer_type` method.

Error I'm seeing:

> Madmin couldn't find attribute or association 'id' on User model.
> 
> We searched these attributes and associations:
> id, name, email, active, created_at, updated_at, oauth_iss, oauth_aud, oauth_sub, first_name, last_name, password, password_confirmation, recovery_password, recovery_password_confirmation, flash_card_sets, credits, consumed_credits

Looks to be blowing up in `madmin/resource.rb:189`:

```ruby
if model.attribute_types.include?(name_string)
          column_type = model.attribute_types[name_string]
          if column_type.is_a? ActiveRecord::Enum::EnumType # Line 189
            :enum
          else
            column_type.type || :string
          end
```

Here's a more complete stack trace when I modify the gem and use the local version:

```plaintext
uninitialized constant Madmin::ActiveRecord::Enum
/Users/clayton/Projects/madmin/lib/madmin/resource.rb:189:in `infer_type'
/Users/clayton/Projects/madmin/lib/madmin/resource.rb:36:in `attribute'
/Users/clayton/Projects/example-app/app/madmin/resources/user_resource.rb:3:in `<class:UserResource>'
/Users/clayton/Projects/example-app/app/madmin/resources/user_resource.rb:1:in `<main>'
```

I tried [writing a more specific test](https://github.com/clayton/madmin/blob/4d5daba7a159efbd4a7556987d462aae36cde75d/test/madmin_test.rb#L27C1-L28C1) in my forked version of madmin that checks for an enum type, but don't get the error there.

Versions:

- Rails v7.1.3.2
- Madmin v1.2.8
- Ruby v3.3.1

**Comment by clayton** [comment]
Tried to recreate the issue with a new Rails app. **Fix is documented below**

Looks like there is an issue when using ActiveRecord session storage.

When you run the `rails generate active_record:session_migration` generator you get this migration:

```ruby
class AddSessionsTable < ActiveRecord::Migration[7.1]
  def change
    create_table :sessions do |t|
      t.string :session_id, :null => false
      t.text :data
      t.timestamps
    end

    add_index :sessions, :session_id, :unique => true
    add_index :sessions, :updated_at
  end
end
```

And if you run `rails g madmin:install` it will generate this resources:

- `app/madmin/active_record/session_store/session_resource.rb`

Once that's present, the error in the original issue starts occurring.

But if you remove:

- `app/madmin/resources/active_record`
- `app/controllers/madmin/active_record`
- The `active_record` namespace in the route

It starts working again.

**Temporary fix:** Remove the session_store resource causing the ActiveRecord namespace issues

**Better fix:** Update madmin generators to skip session storage tables and resources.

**Comment by excid3** [comment]
Could be that we need to use `::ActiveRecord::Enum` so it doesn't try to look in the Madmin namespace.

`          if column_type.is_a? ::ActiveRecord::Enum::EnumType`

Does this reproduce the issue so we can add it to our test suite? https://github.com/clayton/madmin/commit/4d5daba7a159efbd4a7556987d462aae36cde75d

**Comment by clayton** [comment]
Yup, that fixes it.

Broken:

```ruby
if column_type.is_a? ActiveRecord::Enum::EnumType
```

Working:

```ruby
if column_type.is_a? ::ActiveRecord::Enum::EnumType
```
