### ISSUE TITLE
Add a support for model's instance method as resource's attribute

### ISSUE THREAD

**Issue by adiprnm** [excid3/madmin#208]
Hi Chris, I want to thank you for this awesome gem! :fire: 

I have an instance method that needs to be displayed in the index and show page, but it seems it's not supported yet. Would you like to consider it as an enhancement? I would love to open a new PR for this.

**Comment by excid3** [comment]
This is already supported, but I'd like to make it a bit cleaner in the long term.

For now, you can specify `attribute :my_method, field: Madmin::Field::String`

We will probably do something like `field_type: :string` that can make this simpler than specifying the full class eventually.

**Comment by excid3** [comment]
As soon as I wrote that, I realized we already do have a simpler way:

```ruby
attribute :my_method, :string
```

The second argument is optional but allows you to specify the type.

**Comment by adiprnm** [comment]
Thank you, will give it a try!
