### ISSUE TITLE
Webpacker::Manifest::MissingEntryError in Madmin::Dashboard#show

### ISSUE THREAD

**Issue by thewatts** [excid3/madmin#22]
Brand new Rails app w/ a few models generated

`rails new {name} -T --database=postgresql`

Ran through the docs for installation

`rails s` in one tab, `./bin/webpack-dev-server` in another.

Unfortunately, I'm one of those old geezer Rails devs who's behind the times on Webpacker things.

Apologies if I'm missing something simple 😅

![image](https://user-images.githubusercontent.com/1141717/107097027-a2acee00-67d1-11eb-9f1e-63549f3f1966.png)
![image](https://user-images.githubusercontent.com/1141717/107097063-b9ebdb80-67d1-11eb-9518-a88476480b94.png)

**Comment by excid3** [comment]
@thewatts Make sure you're using the beta, not 0.1.1. `bundle add` won't install any pre-releases by default, hence why you're seeing this. 👍

**Comment by excid3** [comment]
In fact, maybe I should just release a 1.0 and call it a day.

**Comment by excid3** [comment]
Done! 🚀

**Comment by thewatts** [comment]
@excid3 - many thanks!

Unrelated issue - but on the same track. Updated my Gemfile to use 1.0

Let me know if you want me to open a new issue.

![image](https://user-images.githubusercontent.com/1141717/107098017-dee14e00-67d3-11eb-96b6-3b299f756cb8.png)

**Comment by excid3** [comment]
You may need to delete the existing madmin files from the previous install and then reinstall. If that fixes it, no need for an issue since the controller templates have changed since the real early version you had before.

If that doesn't fix it, happy to take a look and get that fixed. I will probably need an example app to replicate it with though.

**Comment by thewatts** [comment]
@excid3 💪💪💪

That was the ticket.

Many thanks!

**Comment by excid3** [comment]
Yay! I was hoping I wouldn't have to fix bugs. 😜
