### ISSUE TITLE
Version 2.0.0 throws `Sprockets::FileNotFound` error

### ISSUE THREAD

**Issue by Abdullah-l** [excid3/madmin#231]
I installed the gem from the github repo since the latest version is not yet on rubygems
```rb
gem "madmin", git: 'https://github.com/excid3/madmin.git'
```

It throws this error when navigating to `/madmin`
```
Sprockets::FileNotFound in Madmin::Dashboard#show
Showing /Users/aa/.rvm/gems/ruby-3.3.6/bundler/gems/madmin-89ad662a3451/app/views/madmin/application/_javascript.html.erb where line # raised:

couldn't find file 'trix' with type 'text/css'
```

I believe this might be related to the changes with importmaps

**Comment by excid3** [comment]
Madmin currently expects you have ActionText in your Rails application. Looks like you don't have it installed or it's not accessible to sprockets?

**Comment by ACPK** [comment]
Should it install these as dependencies?
