### ISSUE TITLE
Webpacker::Manifest::MissingEntryError in Madmin::Dashboard#show

### ISSUE THREAD

**Issue by rickavmaniac** [excid3/madmin#25]
Hi,

I install madmin and run rails g madmin:install with succes

But when I try to open /madmin (dashboard) I got this error : 

"Webpacker::Manifest::MissingEntryError in Madmin::Dashboard#show"

Any idea?

**Comment by excid3** [comment]
Make sure you're using the latest version. Sounds like you're on 0.1

**Comment by rickavmaniac** [comment]
Good catch.

The install now is working. Just wondering if this is the interface expected?
![image](https://user-images.githubusercontent.com/65045079/107130111-8e7ff400-6898-11eb-98b3-e01d25dd8080.png)

**Comment by afomera** [comment]
Yeah we've not really focused on design improvements yet, so this is to be expected.
