### ISSUE TITLE
Browser errors after install (into JSP app)

### ISSUE THREAD

**Issue by drnic** [excid3/madmin#29]
I installed madmin into a fresh JSP app (not sure if relevant or not) and in my browser I get the following errors:

<img width="1171" alt="Screen Shot 2021-02-13 at 7 52 51 am" src="https://user-images.githubusercontent.com/108/107826522-c0c9ae00-6dd0-11eb-9492-b40d551af214.png">

**Comment by excid3** [comment]
This should be fixed now. Skypack no longer has the CSS for slimselect for whatever reason... super strange. I just switched to using unpkg for CSS for now.

And it now checks if Rails UJS is already started before starting it. 👍
