### ISSUE TITLE
Allow for custom path name

### ISSUE THREAD

**Issue by andersklenke** [excid3/madmin#40]
First of all thanks for this great gem!

Right now the admin interface lives at `/madmin`, and that is not customisable. I would like it at `/admin` instead. This is doable by doing:
```ruby
namespace :madmin, path: "admin"
```

This introduces a problem with the navigation. The [resource paths](https://github.com/excid3/madmin/blob/master/lib/madmin/resource.rb#L44) are hard coded to `/madmin`.

I can prepare a PR to generate the paths by the route name instead, if that's something you think is a good idea.

**Comment by excid3** [comment]
Yep, go for it.
