### ISSUE TITLE
Named route doesn't seem to be working for non-model admin pages

### ISSUE THREAD

**Issue by dhurba87** [excid3/madmin#47]
I ran into following issue when pulling the latest master. Seems like latest [commit](https://github.com/excid3/madmin/commit/6a6c08bccfdbff2a5e0f288c47173bf06bfc570f) is causing this issue.

![image](https://user-images.githubusercontent.com/7259726/115265150-ac01f180-a156-11eb-9e38-0fff07538f9e.png)

**Comment by excid3** [comment]
Thanks for reporting this @dhurba87 👍 

We may need to do the `table_name` instead like the Rails generators use:

```ruby
ActionText::RichText.table_name
=> "action_text_rich_texts"
```

Rails does this here:
https://github.com/rails/rails/blob/6ebd134a9afb1870f62ff74b96c7d92a94feca6d/railties/lib/rails/generators/named_base.rb#L117-L119

**Comment by dhurba87** [comment]
Awesome! Let me create a PR for this
