### ISSUE TITLE
Support virtual attributes for has_secure_password

### ISSUE THREAD

**Issue by Bramjetten** [excid3/madmin#51]
My `User` model uses `has_secure_password`. This means it has a virtual attribute `password` and it should be editable in madmin.

Currently, madmin doesn't understand this:
`Couldn't find attribute or association 'password' with type '' on User model`

**Comment by excid3** [comment]
Just pushed up d4f7393 with `has_secure_password` support. That should do the trick.

**Comment by Bramjetten** [comment]
Thanks for your quick response! Works like a charm.

After updating I noticed a bug in Safari. I've created a separate PR #53
