### ISSUE TITLE
Bug: `rails generate madmin:views` does not generate navigation and layout views

### ISSUE THREAD

**Issue by vfonic** [excid3/madmin#58]
Steps to repro:

1. `bundle add madmin`
2. `rails g madmin:install`
3. `rails generate madmin:views`

Expected:

Generator creates:

```sh
app/views/layouts/madmin/application.html.erb
app/views/madmin/application/_form.html.erb
app/views/madmin/application/_javascript.html.erb
app/views/madmin/application/_navigation.html.erb
app/views/madmin/application/edit.html.erb
app/views/madmin/application/index.html.erb
app/views/madmin/application/new.html.erb
app/views/madmin/application/show.html.erb
```

Actual:

```diff
- app/views/layouts/madmin/application.html.erb
app/views/madmin/application/_form.html.erb
- app/views/madmin/application/_javascript.html.erb
- app/views/madmin/application/_navigation.html.erb
app/views/madmin/application/edit.html.erb
app/views/madmin/application/index.html.erb
app/views/madmin/application/new.html.erb
app/views/madmin/application/show.html.erb
```

Running:
`rails g madmin:views:navigation` and `rails g madmin:views:layout` explicitly, generates navigation and layout views respectively.

**Comment by excid3** [comment]
Fixed!

I updated the `madmin:views` generator to include everything now. It was missing a couple of the other generators.

Also added a `madmin:views:javascript` generator if you only want to modify that.

**Comment by vfonic** [comment]
Thanks, Chris! You're a legend! :) 🚀 🔥
