### ISSUE TITLE
Madmin is broken on app that skipped javascript (aka web packer)

### ISSUE THREAD

**Issue by afomera** [excid3/madmin#6]
I generated a rails app `rails new foobar --skip-javascript` and upon installing madmin it errors out when loading the dashboard because javascript_pack_tag is not defined.

**Comment by excid3** [comment]
Bug or feature? 🤔 

I don't have any problems only supporting Webpacker for v1.

**Comment by excid3** [comment]
This should be fixed now that we're using Skypack for our Javascript. Gonna close it but we can reopen if needed.
