### ISSUE TITLE
ERROR:  relation "action_mailbox_inbound_emails" does not exist 

### ISSUE THREAD

**Issue by uurcank** [excid3/madmin#68]
`: ERROR:  relation "action_mailbox_inbound_emails" does not exist (PG::UndefinedTable)
LINE 8:  WHERE a.attrelid = '"action_mailbox_inbound_emails`

Does the gem assume action_mailbox installed by default? This gets fixed after I run 

` rails action_mailbox:install `

**Comment by excid3** [comment]
No, it just finds every model it can.

**Comment by uurcank** [comment]
I do not have action mailbox installed in the app but I get the error message. It disappears after I install action mailbox.

**Comment by excid3** [comment]
Yep, we'll get it fixed.

**Comment by excid3** [comment]
Actually, the `madmin:install` already checks to make sure it has a table when it's generating resources.

```ruby
if model.table_exists?
  call_generator "madmin:resource", model.to_s
else
  puts "Skipping #{model} because database table does not exist"
end
```

Did you already have a Madmin resource for the InboundEmails model for some reason?

**Comment by uurcank** [comment]
@excid3 I tested this on Jumpstart Pro template. Action mailbox was not installed. 

If it is not happening on your end it may be an error in my code. I will try again this week.

**Comment by andersklenke** [comment]
@uurcank I just had the same error.

Edit: I was on an old version of Madmin. That could be why.
