### ISSUE TITLE
Check if madmin urls and things work fine if the model in the app has to_param defined

### ISSUE THREAD

**Issue by afomera** [excid3/madmin#7]
ie. we use a to_param method in models to do friendly urls, we should make sure madmin doesn't break on those.

**Comment by excid3** [comment]
Should be fine as Madmin doesn't do anything special here.

- [x] Validate works with custom `to_param`
- [x] Validate can easily add `friendly.find` to use friendly_id in the admin

**Comment by excid3** [comment]
This is done via #39 😍
