### ISSUE TITLE
Feature request: Search

### ISSUE THREAD

**Issue by archonic** [excid3/madmin#72]
I'd love to switch from Adminstrate but I can't do that until Madmin has search 🙏

**Comment by excid3** [comment]
Indeed. We can't use something database-specific like pg_search, and I don't particularly like Ransack.

Maybe we take a similar approach to what Administrate does:
https://github.com/thoughtbot/administrate/blob/main/lib/administrate/search.rb

**Comment by archonic** [comment]
I actually like the way Administrate did their search. I'd be happy with that in Madmin.
