### ISSUE TITLE
Use custom FormBuilder

### ISSUE THREAD

**Issue by itsameandrea** [excid3/madmin#78]
Hi Chris and team!

In my project I'm using a custom FormBuilder that automatically adds certain Stimulus `data-` properties around `rich_text_areas` tags in order to support media attachment:

```
  def rich_text_area(method, options = {})
    default_opts = {data: {'trix-youtube-plugin-target': 'editor'}}
    merged_opts = default_opts.merge(options)
    @template.content_tag :div, data: {controller: 'trix-youtube-plugin'} do
      @template.content_tag :div, data: {'trix-youtube-plugin-target': 'wrapper'} do
        super(method, merged_opts)
      end
    end
  end
```

Is there any easy way to reuse this form builder? Of course, I could just generate all the views and switch it myself but I didn't want to go that far (at least not yet).

**Comment by excid3** [comment]
You should just need to override the form partial to add your builder. https://github.com/excid3/madmin/blob/master/app/views/madmin/application/_form.html.erb#L1

**Comment by itsameandrea** [comment]
Thanks!
