### ISSUE TITLE
Full CI suite

### ISSUE THREAD

**Issue by excid3** [excid3/madmin#8]
Test against everything:

* Ruby 2.7, 3.0
* Rails 6.0, 6.1 (We can use Appraisal for this)
* Postgres, Sqlite, MySQL

See: https://github.com/excid3/noticed/blob/master/.github/workflows/ci.yml

**Comment by BilalBudhani** [comment]
I can take this up. I have been meaning to look into this gem.

**Comment by excid3** [comment]
Finally open sourcing what we've got so far! Hopefully going to get this wrapped up and get the first version out the door very soon.

**Comment by excid3** [comment]
I ended up doing this today to make sure everything was ready for contributions.
