### ISSUE TITLE
Running madmin:install error relation "blazer_uploads" does not exist

### ISSUE THREAD

**Issue by petebytes** [excid3/madmin#88]
/usr/local/bundle/gems/activerecord-6.1.4/lib/active_record/connection_adapters/postgresql/database_statements.rb:19:in `exec': PG::UndefinedTable: ERROR:  relation "blazer_uploads" does not exist (ActiveRecord::StatementInvalid)
LINE 8:  WHERE a.attrelid = '"blazer_uploads"'::regclass

**Comment by petebytes** [comment]
I was able to install successfully by commenting out blazer.

However when I tried to start the application it failed with:
/app/app/madmin/resources/announcement.rb:2:in `<module:Madmin>': Resources is not a class (TypeError)
rails_1 | /usr/local/bundle/gems/madmin-0.1.0/lib/madmin/resources.rb:2: previous definition of Resources was here

**Comment by excid3** [comment]
Was Blazer not fully installed? Madmin looks for all models in your app and will try to create a resource for each one.

Blazer does have an Upload model: https://github.com/ankane/blazer/blob/master/app/models/blazer/upload.rb

It seems that table does not exist in your database?

Also, please paste the full logs from the blazer_uploads error so I can see where it was triggered.
