### ISSUE TITLE
Updating Zeitwerk to `2.5.0.beta2` breaks loading of resources

### ISSUE THREAD

**Issue by arschrier** [excid3/madmin#92]
After updating Zeitwerk to `2.5.0.beta2`, Rails expects Madmin resources to be namespaced.

For example, `madmin/resources/customer_resource` is expected to define `Resources::CustomerResource`.

The actual error on build:
```
Zeitwerk::NameError: expected file /app/app/madmin/resources/customer_resource.rb to define constant Resources::CustomerResource, but didn't
```

**Comment by arschrier** [comment]
Telling Rails to collapse the resources directory fixed the issue. I did so by adding the following to `config/application.rb`:

```ruby
Rails.autoloaders.main.collapse('app/madmin/resources')
```

**Comment by excid3** [comment]
Is this something that changed specifically in Zeitwerk 2.5?

**Comment by arschrier** [comment]
Spoke too soon! Thought this was related to Zeitwerk itself, but it appears this has to do with the way Rails now auto loads paths.

This is the breaking commit from Rails: https://github.com/rails/rails/commit/2306a8e645627a7913e161b76eeeb7ee6e6724a9.

I am not an expert here, but is Rails eager loading the directory before engines are initialized?

**Comment by excid3** [comment]
Could be that the Madmin initializer isn't running early enough now. We do a similar thing to make sure the autoload paths are added before they get frozen.

https://github.com/excid3/madmin/blob/master/lib/madmin/engine.rb#L3

**Comment by mattpolito** [comment]
Can confirm... resource loading does not appear to work in Rails 7 alpha

**Comment by excid3** [comment]
PRs welcome if you figure out what's going on. 👍

**Comment by mattpolito** [comment]
@excid3 of course... trying to figure it out myself :-)

**Comment by excid3** [comment]
This took some serious time to figure out but I got it working. 🔥

**Comment by mattpolito** [comment]
@excid3 did you come across something that shows path loading needs to happen 'before configuration' or was that just the hook placement that ended up working?

**Comment by excid3** [comment]
I had to dig through the Rails source code to figure it out. Couldn't find any examples or anything. The previous stuff was what I had found in a blog post, but this works consistently across all Rails versions using `before_configuration`. I didn't even know that was a callback you could use until I started reading the Rails source. 😅
