### ISSUE TITLE
Support ActiveRecord encryption

### ISSUE THREAD

**Issue by excid3** [excid3/madmin#96]
The encrypted attributes use a `_digest` column to store the encrypted values. We can ignore these columns, but add attributes to the Madmin resource for the attribute.

**Comment by jacobdaddario** [comment]
Hey! It looks like Madmin already handles columns with `_digest` in the name. That should be rolled into the behavior for `has_secure_pasword`.

That said, I was looking at some of the previews for ActiveRecord encryption, and I don't think the columns actually have `_digest` in the name. Do you want to add support for that new feature?

**Comment by excid3** [comment]
We just need to make sure it works with the built-in encryption. 👍

**Comment by jacobdaddario** [comment]
If that's the case I think we're good to close this issue. There was a check for the built-in hashing in the current version of Rails last I looked at Madmin.

**Comment by excid3** [comment]
I figure we should add an example in the dummy app and a test case I figure. That way we can know it works.

**Comment by esmale** [comment]
I created a new app running on the current Rails 7 alpha, installed madmin, set up an encrypted attribute ("identifier"), and confirmed that madmin handles everything just fine.  The attribute is properly encrypted on the database, but the un-encrypted text renders to the browser just fine.

Adding tests for this, though, has me completely stumped.  ActiveRecord Encryption only exists for Rails 7, but the gem is currently set up to be supported for Rails 6+.  Outside of needing to figure out how to run a test only when considering a specific version of Rails, would also need to figure out how to only apply the `encrypts :identifier` line to the User model if the tests are running through Rails 7.

So....thoughts?

**Comment by excid3** [comment]
@esmale Great question.

We can conditionally include that I think. 

```ruby
class model
  if Rails.gem_version > Gem::Version.new("7.0.0.alpha")
    encrypts :example
  end
end
```

Same can be applied to the test so it only runs on Rails 7 as well.

**Comment by excid3** [comment]
Added an example encrypted field to the User model.
