### ISSUE TITLE
field_for_type Argument Error Doesn’t Read as Expected

### ISSUE THREAD

**Issue by jacobdaddario** [excid3/madmin#99]
I’m opening this issue in relation to some of the trouble I ran into with #98. After more investigation I believe the error that can be raised in `field_for_type` isn’t functioning quite as expected. Particularly the names being inserted into the error string don’t make sense. I believe it’s catching an error not expected by the original implementation.

I’ll continue to investigate and document my findings here when I get #98 finished.

**Comment by excid3** [comment]
<img width="1137" alt="Screen Shot 2021-09-23 at 12 11 54 AM" src="https://user-images.githubusercontent.com/67093/134457457-15e64b80-a093-4106-a86f-39b51647b0f4.png">

This should be much more clear (and we can continue improving it) as needed.
